### PR TITLE
impl AsRef<[u8]>, Borrow<[u8]> for SmallString

### PR DESCRIPTION
**Pull request by bachue**

### CODE REVIEW

**Comment by shelvacu** [comment]
Doesn't giving out a `&mut [u8]` violate the safety garuntee that the string will always be valid UTF-8?

**Comment by bachue** [comment]
@shelvacu Yes, you're right.

**Comment by bachue** [comment]
@shelvacu Please review again

**Comment by shelvacu** [comment]
I'm so sorry, I'm not a maintainer. Just giving my thoughts in the hope they'd be useful.

**Pull request merged**
