### PR TITLE
[version]: bumped version of smallvec

### PR DESCRIPTION
**Pull request by appetrosyan**
Version bump of `smallVec`.

### CODE REVIEW

**Comment by murarth** [comment]
I don't believe this change is necessary. Given how cargo uses semver in dependencies (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio), `smallstr` can be compiled using `smallvec` 1.8 as a dependency without any changes, as going from 1.1 to 1.8 is only a minor version change. Running `cargo update` should update all dependencies to the latest applicable version.

**Comment by appetrosyan** [comment]
Unfortunately, without this change a program that uses both this version of smallvec and the hitherto unreleased version of smallstr that supports no_std with serde refuses to compile. It might be fine in crates in a single workspace but a library that uses another library that depend on smallstr breaks. 

I wouldn't have created the PR, if I wasn't certain that it did something.

**Comment by murarth** [comment]
I really don't think `smallstr`'s dependency version is the root cause of this issue. It may be a bug in Cargo's dependency resolver. If you search their issue tracker for the phrase "failed to select a version", a number of such bugs turn up. I see that a common workaround for these bugs is to delete the `Cargo.lock` file and build the project again. Have you tried that?

**Comment by appetrosyan** [comment]
@murarth you were right. After a bit of debugging I did find that the crate that failed to compile was a binary crate that checked in its `Cargo.lock`. I agree that this pull request is redundant. Closing.

**Pull request closed without merging**
